Fix gcc compilation error due to unitialized pointers
[   19s] /home/abuild/rpmbuild/BUILD/sec-gate-oidc-1.0.8/idps/idp-github.c:184:5: error: 'fedUser' may be used uninitialized in this function [-Werror=maybe-uninitialized]
[   19s]      fedUserFreeCB(fedUser);
[   19s]      ^~~~~~~~~~~~~~~~~~~~~~
[   19s] /home/abuild/rpmbuild/BUILD/sec-gate-oidc-1.0.8/idps/idp-github.c:183:5: error: 'fedSocial' may be used uninitialized in this function [-Werror=maybe-uninitialized]

Change-Id: Iee38cb629f89f0c2fa05c7c36364589ab273c608
Signed-off-by: Stephane Desneux <stephane.desneux@iot.bzh>